Independent game logic
Lokideos/thinknetica_black_jack pull request #5
Opened 2018-09-28 21:10 UTC by Lokideos

В рамках данного пул реквеста был реализован следующий функционал:

* Функции, связанные с игровой логикой, были перенесены из интерфейса в отдельный файл;
* Игровой интерфейс был уточнен и дополнен в соответствии с новыми требованиями.

2018-09-30 10:08 UTC, vkurennov requested changes

2018-09-30 10:08 UTC, vkurennov commented on app_data/deck.rb
> +  SUITS = ["\u2660", "\u2665", "\u2663", "\u2666"].freeze
Номиналы и масти карт стоит вынести в константы класса Card, т.к. это именно к карте относится.

2018-09-30 10:08 UTC, vkurennov commented on app_data/deck.rb
> +  RANKS_WITH_VALUES = [["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7], ["8", 8],
1. Если ты используешь вложенные массивы, то это верный знак, что нужно использовать хеш. В данном случае точно.
2. Здесь можно упростить, т.к. очки карт до валета легко получаются из номинала. Валет, дама и король имеют одинаковое значение, тоже можно сгруппировать.

2018-09-30 10:08 UTC, vkurennov commented on app_data/deck.rb
> +  RANKS_WITH_VALUES = [["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7], ["8", 8],
Также можно перенести определение кол-ва очков в класс карты. Т.е. карте передаем только масть и номинал, а она сама определяет свое кол-во очков (умеет его возвращать). Для туза базовое значение можно взять в 11 и менять его при подсчете очков, если нужно.

2018-09-30 10:08 UTC, vkurennov commented on app_data/card.rb
> +class Card
Стоит добавить проверку на возможное значение и масть карт. Сейчас ничто не мешает создать карту, например, `128*`

2018-09-30 10:08 UTC, vkurennov commented on app_data/game_session.rb
> +    deck.cards = deck.fill_deck
Эта операция и так происходит при вызове конструктора Deck

2018-09-30 10:08 UTC, vkurennov commented on app_data/deck.rb
> +  def remove_card(card)
Вместо явного удаления карты, лучше реализовать метод колоды, который выдает карту из колоды и сразу ее удаляет. Удалять карту из колоды - это не ответсвенность внешнего кода, это ответсвенность класса колоды. Стоит один раз забыть удалить карту из колоды после ее получения, как вся механика игры нарушится. поэтому лучше сразу исключить такую возможность.

2018-09-30 10:08 UTC, vkurennov commented on app_data/game_session.rb
> +  def fill_hand_for(actor, deck)
У тебя здесь слишком низкоуровневая работа с множеством классов, т.е. ты забираешь у этих классов ответсвенность, а нужно наоборот - передавать. Стоит ввести класс Hand, который будет хранить карты на руке у игрока/дилера и подсчитывать кол-во очков (у класса игрока будет атрибут типа Hand). А также изменить метод выдачи карты у колоды, как я выше написал. 

Тогда здесь будет всего 2 действия: взять карту  из колоды, добавить ее игроку. Все остальное произойдет автоматически.

2018-09-30 10:08 UTC, vkurennov commented on app_data/game_session.rb
> +  def check_for_defeat
Если метод называется  со слова `check` - то он только что-то проверяет, а не делает еще какие-то действия (с банком в данном случае). Т.е. это должен быть метод-предикат. А в руби принято их называть со знаком вопроса в конце и без слова `check` в начале.

2018-09-30 11:07 UTC, mr-koww commented on app_data/deck.rb
> +  def remove_card(card)
Немного подскажу - можно использовать метод pop

2018-10-02 08:48 UTC, vkurennov approved these changes

2018-10-02 22:47 UTC, merged